Support for using stdcbench for mcs51.
git-svn-id: http://svn.code.sf.net/p/sdcc/code/trunk@10669 4a8a32a2-be11-0410-ad9d-d568d2c75423

diff --git a/sdcc-extra/historygraphs/execute_benchmark-mcs51 b/sdcc-extra/historygraphs/execute_benchmark-mcs51
--- a/sdcc-extra/historygraphs/execute_benchmark-mcs51
+++ b/sdcc-extra/historygraphs/execute_benchmark-mcs51
@@ -12,8 +12,8 @@ if [ $# != 2 ]; then
 	exit 1
 fi
 
-if ! command -v $STM8FLASH &> /dev/null; then
-	echo "$STM8FLASH not found!";
+if ! command -v $EC2WRITEFLASH &> /dev/null; then
+	echo "$EC2WRITEFLASH not found!";
 	exit 1
 fi
 
